services:
  ignition-hf-gateway:
    image: ghcr.io/ignitionnetworks/ignition-hf-gateway:${VERSION:-latest}
    network_mode: host
    volumes:
      - ./config:/config
      - ./prompts:/prompts
      - ./data:/data
      - ./logs:/logs
    environment:
      - IGNITION_CONFIG=/config/config.jsonc
      - IGNITION_LOG_DIR=/logs
      - IGNITION_AUTH_DB=/data/auth.db
      - IGNITION_MSG_DB=/data/messages.db
      - IGNITION_PROMPT_DIR=/prompts
    restart: unless-stopped
